#!/usr/bin/env python

# Copyright (C) 2021 LEIDOS.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

"""
Subscribe from CARMA :autoware_msgs::VehicleCmd
    Topic: /hardware_interface/vehicle_cmd

Publish to CARLA :ackermann_msgs::AckermannDrive
    Topic: /carla/{}/ackermann_cmd
"""
import rospy
from ackermann_msgs.msg import AckermannDrive
from autoware_msgs.msg import VehicleCmd
from cav_msgs.msg import GuidanceState

pub = None
guidance_state = GuidanceState.STARTUP
init_status = True
init_cmd = AckermannDrive()

def guidance_state_callback(guidance_state_msg):
    """
    callback for guidance state subscribing from CARMA
    guidance_state_msg type:
        cav_msgs::GuidanceState
    """
    global init_status
    global init_cmd
    global guidance_state
    guidance_state = guidance_state_msg.state
    if guidance_state == GuidanceState.ENGAGED and init_status:
        init_status = False
        ## providing initial ackermann command to carla virtual vehicle
        init_cmd.speed = 10
        init_cmd.acceleration = 2
        init_cmd.steering_angle = 0
        pub.publish(init_cmd)

def vehicle_cmd_callback(vehicle_cmd):
    """
    callback for vehicle cmds subscribing from CARMA
    vehicle_cmd type:
        autoware_msgs::VehicleCmd
    """

    if guidance_state != GuidanceState.ENGAGED:
        return
    else:
        ackermann_drive = AckermannDrive()
        ackermann_drive.speed = vehicle_cmd.ctrl_cmd.linear_velocity
        ackermann_drive.acceleration = vehicle_cmd.ctrl_cmd.linear_acceleration
        ackermann_drive.steering_angle = vehicle_cmd.ctrl_cmd.steering_angle
        ## publishing ackermann drive msg to CARLA virtual vehicle
        pub.publish(ackermann_drive)


def vehicle_cmd_to_ackermanndrive():
    """
    mainloop
    """
    global pub
    rospy.init_node('carma_to_carla_vehicle_cmd')
    role_name = rospy.get_param('/role_name', 'ego_vehicle')
    pub = rospy.Publisher('/carla/{}/ackermann_cmd'.format(role_name), AckermannDrive, queue_size=1)
    rospy.Subscriber('/hardware_interface/vehicle_cmd', VehicleCmd, vehicle_cmd_callback, queue_size=1)
    rospy.Subscriber('/guidance/state', GuidanceState, guidance_state_callback, queue_size=1)
    rospy.spin()


if __name__ == '__main__':
    print("carma_to_carla_vehicle_cmd")
    vehicle_cmd_to_ackermanndrive()
