/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_mosaic_fed_carla_libcarla_CarlaClient */

#ifndef _Included_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
#define _Included_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    init_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_init_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    tick_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_tick_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    setSynchronous_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_setSynchronous_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    connect_
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_connect_1
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    loadWorld_
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_loadWorld_1
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    reloadWorld_
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_reloadWorld_1
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getActor_
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getActor_1
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getActorIds_
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getActorIds_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getManagedActors_
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getManagedActors_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    createActor_
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_createActor_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getCurrentTimestep_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getCurrentTimestep_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    applySettings_
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_applySettings_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    loadTransform_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_loadTransform_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getClientVersion_
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getClientVersion_1
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_mosaic_fed_carla_libcarla_CarlaClient
 * Method:    getServerVersion_
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_mosaic_fed_carla_libcarla_CarlaClient_getServerVersion_1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
