#
# LightBarIndicatorControllers.msg
#
# @author Misheel Bayartsengel
# @version 0.1
# 
# Published by LightBarManager.
# This msg indicates which indicators are controlled by which component
# 
string green_solid_owner
string green_flash_owner
string yellow_sides_owner
string yellow_dim_owner
string yellow_flash_owner
string yellow_arrow_left_owner
string yellow_arrow_right_owner
string yellow_arrow_out_owner
